version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: FullStackDemo.Server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=FullStackDemoDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
    networks:
      - fullstack-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - fullstack-network

  frontend:
    build:
      context: .
      dockerfile: fullstackdemo.client/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge
